version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:16.20

    working_directory: ~/repo

    steps:
      - checkout

      # Backend install
      - run:
          name: Install Backend
          command: npm install --legacy-peer-deps

      # Frontend install + build
      - run:
          name: Build Frontend
          command: |
            cd client
            npm install --legacy-peer-deps
            CI=false npm run build

      # Deploy
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@63.180.236.1 "
              cd ~/place-tracker &&
              git fetch origin &&
              git reset --hard origin/main &&
              docker compose down --remove-orphans || true &&
              docker compose up --build -d
            "

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-deploy
