version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.10

    steps:
      - checkout

      - run:
          name: Install Backend Dependencies
          command: npm install

      - run:
          name: Install Frontend Dependencies
          command: |
            cd client
            npm install

      - run:
          name: Build Frontend
          command: |
            cd client
            npm run build

      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@63.180.236.1 "
              cd ~/place-tracker &&
              git pull origin main &&
              docker compose down &&
              docker compose up --build -d
            "

workflows:
  build-workflow:
    jobs:
      - build-and-test
